[llm]
name = "qwen-max"
temperature = 0.01

[embedding]
name = "BAAI/bge-base-zh-v1.5"
dim = 768

[rerank]
name = "BAAI/bge-reranker-large"
topk = 10

[retrieve]
topk = 30
similarity_cutoff = 0.4

[database]
host = "127.0.0.1"
port = 5666
user = "postgres"
password = "she4waeJ_uquahg7goh4aewu"
