[llm]
provider = "qwen"
name = "qwen-max"
temperature = 0.01

[chunk]
window_size = 5

[embedding]
name = "BAAI/bge-large-en-v1.5"
dim = 1024

[rerank]
name = "BAAI/bge-reranker-large"
topk = 15

[retrieve]
topk = 50
similarity_cutoff = 0.3

[database]
host = "127.0.0.1"
port = 5666
user = "postgres"
password = "she4waeJ_uquahg7goh4aewu"
